### ISSUE TITLE
Generate automatic reminder for entries in Draft status

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#105]
For the record that has warning flags (those that can't be ignored for validation) and if those hasn't been resolved by the submitter within a month, please send a reminder asking to address the issues to proceed with the further steps in approval and validation. It would be good if the email would contain a workflow outlining the validation steps and actions.

**Comment by lmrodriguezr** [comment]
Monthly reminders are sent for ALL entries in draft status. Was there a different point not covered? Closing for now, please feel free to reopen

**Comment by uqmchuvo** [comment]
Ok, great, thanks!
