### ISSUE TITLE
Autofilling grammar in etymology of higher taxa names

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#119]
When etymology needs to be added for a new higher taxa, a section on grammar can be autoprefilled as it is standard grammar for each higher rank. For example, families and orders are always "fem. pl. n."  while classes and phyla are always "neut. pl. n.".

**Comment by lmrodriguezr** [comment]
I believe this is already supported by the "Automatically fill the etymology" button. See the [video tutorial](https://disc-genomics.uibk.ac.at/seqcode/help/etymology). Or did you mean something different?

**Comment by lmrodriguezr** [comment]
Hello @uqmchuvo, please let me know if there is a missing feature here, otherwise I think we can close this issue.

**Comment by lmrodriguezr** [comment]
@uqmchuvo I'm closing this issue now, but please feel free to reopen if needed

**Comment by uqmchuvo** [comment]
Thanks! This is Ok to be closed.
