### ISSUE TITLE
Name and list observers

### ISSUE THREAD

**Issue by lmrodriguezr** [seq-code/registry#131]
Users should be able to "observe" Name and Register models, so they are notified by email on changes and new correspondence.

- [x] Name and Register: `observers` in the models
- [x] Controllers for `observe` and `unobserve`
- [x] View options for `observe` and `unobserve`
- [x] Initial DB task to mark all users associated to a model as observers (`*_by` and those with messages in correspondence)
- [x] Automatically register observers after creating, editing, claiming, or commenting on names (or registers)
- [x] Email settings for notifications on change and notifications on messages.
- [x] Email notifications on correspondence
- [x] Email notifications on change

**Comment by lmrodriguezr** [comment]
@FangYuan0059 Would you like to join me on implementing this?

**Comment by FangYuan0059** [comment]
Yes, for sure. I will look at them and see if I have questions.

Best,
Fang

**Comment by lmrodriguezr** [comment]
Great! Thanks! I've just started implementing something in the `observers` branch. Please feel free to work directly in that branch
