### ISSUE TITLE
Inconsistencies between the registered name and final publication

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#18]
If the registered name has all the details except DOI and the user sent it to the review by SeqCode curator, it is still possible that there could be some modification after or during the peer-review. In such cases, we encourage users to modify the record in the registry except that some users may forget to do so. I suggest adding a warning message when authors are about to add new publication to existing record saying "Please carefully review that all registration details are correct and updated as per submitted publication". It would be great if the system could also attempt to perform some simple checks such as the  presence of registered name and its type in the submitted paper. If it detects any inconsistencies, it should prevent user from proceeding to the next step.

**Comment by lmrodriguezr** [comment]
Most of this is currently handled by notifications, except the automated evaluation of types (not currently planned)
