### ISSUE TITLE
Registration of 'species lineague'

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#20]
Users can view all new names their registered and associated with the same type under the title "species lineague". However, currently it is a bit confusing because the associated names are not appearing the hierarchical order. Also all parent taxa will appear without the proposed rank information. Shall we sort them hierarchically and append the rank or the rank still needs to be confirmed by the user?? Also does the system propose all higher taxa names regardless the existing classification?? I meant do we expect user to actually specify whether or not this whole lineague is new or what parent taxa are new? Or this workflow goes from the idea that use select the pathway where new species is proposed and parent taxa does not exist? but then he might need to actually specify what ranks are missing, e.g. is that family and order or order and class. The proposals can be patched where some parent taxa are existing and others are not.

**Comment by lmrodriguezr** [comment]
This was resolved by *only* including the name that is being actively registered by the user, instead of the whole list of names per guided registration.

I believe the latter part can be covered by #13
