### ISSUE TITLE
Priority time and date

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#29]
Can we simulate a validation process with the validated name as a test? 
Will the registry reflect the time and date of validation as articulated in the SeqCode? 
The time could be reflected in UTC I guess for comparison.
It would be good to test how this will look like.

**Comment by uqmchuvo** [comment]
In LPSN, priority will be determined by date of publication in IJSEM and both effective and valid publication is given. Since we decided to reflect the priority based on completion of registration, we might need a dedicated field called "Validation time&date". I am not sure if you were planning to include this in the message below the taxon name or into the dedicated field that can be used by others (e.g., GTDB will need this information to be easily retrievable for each name).

**Comment by lmrodriguezr** [comment]
This is currently reflected in the Registry Lists (not in the name page). The priority time and date is currently determined by the notification of publication (i.e., when the user notifies the Registry that the publication is out, and submits the PDF).
