### ISSUE TITLE
Explanatory notes on the home page 

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#4]
For new users it is not clear why there is already so many registered names and what is identified names. The main purpose of registry is to list names validly published under the SeqCode but it also has other functions such as auto-discovery of Candidatus taxa and names from ICNP as well. This should clearly stated on the fist page.

**Comment by lmrodriguezr** [comment]
Reformatting the splash message should help here

**Comment by lmrodriguezr** [comment]
This has now been addressed, but feel free to reopen if needed
