### ISSUE TITLE
Inconsistent with type genus: failing check

### ISSUE THREAD

**Issue by lmrodriguezr** [seq-code/registry#53]
See https://disc-genomics.uibk.ac.at/seqcode/names/23484

**Comment by MarikePalmer** [comment]
Another inconsistent with type genus bug - names ending in a (e.g., Duberdicusella in my draft registry list [seqco.de/r:xqyhj6of])

**Comment by lmrodriguezr** [comment]
This name has been deleted since, but it was probably related to the inconsistent grammar issue already solved
