### ISSUE TITLE
Etymology help resources

### ISSUE THREAD

**Issue by lmrodriguezr** [seq-code/registry#81]
Add a list of resource links dealing with etymology, grammar, etc to the help message of the etymology table.

**Comment by lmrodriguezr** [comment]
@MarikePalmer @uqmchuvo any suggestions here? If not, I'll mark this issue as complete :)

**Comment by MarikePalmer** [comment]
I don't think there is anything more at the moment that needs adding, although a couple of links to resources/papers dealing with it was suggested at some point? But I haven't spent time on thinking about which ones...

**Comment by uqmchuvo** [comment]
Please don't close this now. I might add few sources today.

**Comment by uqmchuvo** [comment]
Well, not today haha 
Wait till tomorrow :)

**Comment by uqmchuvo** [comment]
Hi Miguel

I believe that we can add the following resources: 

- Appendix 9 of the ICNP: https://doi.org/10.1099/ijsem.0.000778

- Oren A. How to name new taxa of archaea and bacteria. Bergey's Manual of Systematics of Archaea and Bacteria. 2015 Apr 17:1-24. https://doi.org/10.1002/9781118960608.bm00008.pub2
-
- Link to LPSN page (Can we? Do we provide other links to LPSN? I need to double-check, sorry): https://lpsn.dsmz.de/text/etymology

- Latin dictionaries (I am using mostly Perseus but other dictionaries can be of help): https://www.lexilogos.com/english/latin_dictionary.htm

**Comment by lmrodriguezr** [comment]
Great, thanks! I'm adding these and closing the issue for now, but please feel free to reopen if additional resources come to mind.
