### ISSUE TITLE
Automatic check for the presence of "Candidatus" in newly submitted names

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#89]
Implement an auto-check that generate a warning message if the status Candidatus is present in newly deposited names. Authors suppose to remove this status himself before submitting the entry. 

**_Caution_**: this should not be confused with exisiting Candidatus names and only implemented for newly added names. Therefore, the system needs to take care of removal of this status when existing Candidatus name in the registry is claimed for validation and generation of a warning for newly deposited names that contains this status.

**Comment by lmrodriguezr** [comment]
Already implemented
